apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: cluster-b-user
  namespace: target
  labels:
    strimzi.io/cluster: cluster-b
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Underlying Kafka Connects internal topics used to store configuration, offsets or status
      - resource:
          type: group
          name: mirrormaker2-cluster
        operation: Read
      - resource:
          type: topic
          name: mirrormaker2-cluster-configs
        operation: All
      - resource:
          type: topic
          name: mirrormaker2-cluster-status
        operation: All
      - resource:
          type: topic
          name: mirrormaker2-cluster-offsets
        operation: All
        # MirrorSourceConnector
      - resource: # Needed for every topic which is mirrored
          type: topic
          name: "*"
        # MirrorSourceConnector

        operation: All
      - resource:
          type: cluster
        # MirrorCheckpointConnector

        operation: Describe
      - resource:
          type: topic
          name: cluster-a.checkpoints.internal
        operation: Describe
      - resource:
          type: topic
          name: cluster-a.checkpoints.internal
        operation: Write

      - resource:
          type: topic
          name: cluster-a.checkpoints.internal
        operation: Create
      - resource: # Needed for every group for which the offset is synced
          type: group
          name: "*"
        operation: Read
      - resource: # Needed for every group for which the offset is synced
          type: group
          name: "*"
        operation: Describe
    # MirrorHeartbeatConnector => needed only if the connector is enabled

# - resource:
#     type: topic
#     name: heartbeats
#   operations:
#     - Read
#     - Create
#     - Describe
#     - Write
